# Generated by Django 6.0.2 on 2026-05-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_telegram_id_customuser_telegram_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramauthsession',
            name='code',
        ),
        migrations.AddField(
            model_name='telegramauthsession',
            name='collected_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telegramauthsession',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='telegramauthsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Telegram kutilmoqda'), ('awaiting_contact', 'Kontakt kutilmoqda'), ('awaiting_name', 'Ism kutilmoqda'), ('ready', 'Auth tayyor'), ('verified', 'Tasdiqlandi'), ('expired', "Muddati o'tdi")], default='pending', max_length=20),
        ),
    ]
