# Generated by Django 6.0.2 on 2026-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_telegramauthsession_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauthsession',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
