# Generated by Django 6.0.2 on 2026-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_note',
            field=models.TextField(blank=True, help_text='Vazifa haqida qisqacha izoh'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_pdf',
            field=models.FileField(blank=True, help_text='Vazifa PDF fayli (ixtiyoriy)', null=True, upload_to='homework/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text="Dars haqida ma'lumot — talaba nimani o'rganadi"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
