# Generated by Django 6.0.2 on 2026-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_homework_note_lesson_homework_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Modul uchun rasm (kvadrat, JPG/PNG)', null=True, upload_to='modules/'),
        ),
    ]
